version: '3.8'

services:
  api:
    image: unchained-local-node
    env_file: .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.blackfury-api.rule=Host(`api.blackfury.localhost`)'
      - 'traefik.http.services.blackfury-api.loadbalancer.server.port=3000'
    working_dir: /app/node/coinstacks/blackfury/api
    command: yarn nodemon
    volumes:
      - ../../..:/app
    networks:
      - blackfury

networks:
  blackfury:
    name: blackfury_default
    external: true